Toolchain: Build "driver-aarch64.o" for native SerenityOS GCC
The GCC port would otherwise fail to link for AArch64:
"undefined reference to `host_detect_local_cpu(int, char const**)'".

`host_detect_local_cpu` won't actually work in serenity though since
we don't have a `/proc/cpuinfo` file. This simply means `-march=native`,
`-mcpu=native` and `-mtune=native` will be ignored.